spring.application.name=portal-de-receitas
#server.port=8080

# Desabilitar open-in-view para evitar warnings
#spring.jpa.open-in-view=false

# Configurar usuário e senha para o Spring Security
#spring.security.user.name=admin
#spring.security.user.password=admin

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect