# Pode modificar o que precisar so se atente aos comentarios e no que voce poe pois pode fazer o trabalho parar de rodar!!!!!!
# Nome da aplicação
spring.application.name=portal-de-receitas

# Define a porta em que a aplicação será executada
#server.port=8080

# Desabilitar open-in-view para evitar warnings sobre gerenciamento de sessão
# Isso pode ajudar a evitar problemas de desempenho, mas pode afetar o carregamento de dados
#spring.jpa.open-in-view=false

# Configurações de segurança (comentadas neste caso)
# Define o nome de usuário e a senha padrão para o Spring Security
# Se não estiver usando segurança, essas linhas podem ser removidas
#spring.security.user.name=admin
#spring.security.user.password=admin

# Configurações do banco de dados H2 em memória
spring.datasource.url=jdbc:h2:mem:testdb  # URL de conexão com o banco de dados H2
spring.datasource.driverClassName=org.h2.Driver  # Classe do driver do H2
spring.datasource.username=root  # Nome de usuário para conexão com o banco de dados
spring.datasource.password=root  # Senha para conexão com o banco de dados

# Configuração da plataforma do Hibernate para o H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect  # Dialeto do Hibernate para o H2
